version: "3.8"
services:
  store-redis:
    container_name: store-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: flyingrko/store-redis
    ports:
      - "6379:6379"
  store-database:
    container_name: store-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: flyingrko/store-database
    environment:
      - MARIADB_DATABASE=store
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  store-app:
    container_name: store-app
    build: .
    depends_on:
      - store-database
      - store-redis
    image: flyingrko/store-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
    ports:
      - "80:8080"
    restart: always
